services:
  - type: web
    name: nestjs-backend
    env: node
    rootDir: server
    buildCommand: node fix-build.js && pnpm build
    startCommand: node dist/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false # Set this manually in Render dashboard
      - key: SUPABASE_PROJECT_URL
        sync: false # Set this manually in Render dashboard
      - key: SUPABASE_ANON_KEY
        sync: false # Set this manually in Render dashboard
      - key: JWT_SECRET
        sync: false # Set this manually in Render dashboard
      - key: JWT_REFRESH_SECRET
        sync: false # Set this manually in Render dashboard
      - key: JWT_EXPIRATION_TIME
        value: "3600" # 1 hour
      - key: JWT_REFRESH_EXPIRATION_TIME
        value: "86400" # 24 hours
      - key: PORT
        value: "3002"
      - key: CORS_ORIGIN
        value: "https://{{RENDER_SERVICE_NAME}}.onrender.com" # Will be replaced with actual frontend URL 